"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col container m-auto min-h-screen`}
      >
        <div className="flex max-w-screen justify-between px-[120px]">
          <div className="flex gap-2 py-2 items-center">
            <Link href={"/"}>
              <Image
                src="/Icons/Logo.svg"
                alt="Food Delivery Logo"
                width={31.26}
                height={26.76}
              />
            </Link>
            <Link href={"/"}>
              <button
                className={`px-4 py-2 ${
                  pathname === "/" ? "text-[#18BA51]" : ""
                }`}
              >
                НҮҮР
              </button>
            </Link>
            <Link href={"/dashboard"}>
              <button
                className={`px-4 py-2 ${
                  pathname === "/dashboard" ? "text-[#18BA51]" : ""
                }`}
              >
                DASHBOARD
              </button>
            </Link>
          </div>
        </div>
        <div className="flex flex-col container justify-center">{children}</div>
      </body>
    </html>
  );
}
